export default defineAppConfig({
    projects: [
        {
            id: '85808fd2-2277-4eae-a77c-505240ce6787',
            title: 'DragonX Platform',
            listed: true,
            slug: 'dragonx',
            type: 'Front End Developer',
            cover: '/projects/dragonx/dragonx.jpg',
            client: 'Dragon Capital',
            clientLogo: null,
            partner: null,
            completed: 'Jan 2021 - Mar 2023',
            site: 'dragonx.com.vn',
            stack: [
                {
                    id: '923a339b-6c21-4777-a18d-99d6525c8840',
                    name: 'Vue',
                    color: 'purple',
                },
                {
                    id: '923a339b-6c21-4777-a18d-99d6525c8840',
                    name: 'Composition API',
                    color: 'purple',
                },
            ],
            role: 'Front End Developer',
            lead: 'Building the new platform for Dragon Capital.',
            awards: null,
            pageContent: [
                {
                    object: 'block',
                    id: '8297cd08-c819-4455-bfe6-d3e948e6dc07',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-23T14:58:00.000Z',
                    last_edited_time: '2024-03-05T23:57:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'paragraph',
                    paragraph: {
                        rich_text: [
                            {
                                type: 'text',
                                text: {
                                    content: 'DragonX is a fund investment app launched in 2021 by Dragon Capital(DCVFM). It’s designed to enhance user experience and meet individual investors’ needs. Key features include a user-friendly interface, easy account opening via eKYC and e-signature, advanced security standards, and integration of investment insights and educational content.',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'DragonX is a fund investment app launched in 2021 by Dragon Capital(DCVFM). It’s designed to enhance user experience and meet individual investors’ needs. Key features include a user-friendly interface, easy account opening via eKYC and e-signature, advanced security standards, and integration of investment insights and educational content.',
                                href: null,
                            },
                        ],
                        color: 'default',
                    },
                },
                {
                    object: 'block',
                    id: '8297cd08-c819-4455-bfe6-d3e948e6dc07',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-23T14:58:00.000Z',
                    last_edited_time: '2024-03-05T23:57:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'paragraph',
                    paragraph: {
                        rich_text: [
                            {
                                type: 'text',
                                text: {
                                    content: '\n' +
                                        'The DragonX platform includes 3 sites: ',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: '\n' +
                                    'The DragonX platform includes 3 sites: ',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: '\n' +
                                        'DragonX website (For investors), DragonX admin (for administration) and DragonS (for introducers or marketers)',
                                    link: null,
                                },
                                annotations: {
                                    bold: true,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: '\n' +
                                    'DragonX website (For investors), DragonX admin (for administration) and DragonS (for introducers or marketers)',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: '\n' +
                                        '. Among them, DragonX web and DragonX admin are the two main websites.',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: '\n' +
                                    '. Among them, DragonX web and DragonX admin are the two main websites.',
                                href: null,
                            },
                        ],
                        color: 'default',
                    },
                },
                {
                    object: 'block',
                    id: '1db6580a-87dc-4561-90f8-e6fc40830611',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T13:07:00.000Z',
                    last_edited_time: '2024-01-30T13:07:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'image',
                    image: {
                        caption: [],
                        type: 'file',
                        file: {
                            url: '/projects/dragonx/home.png',
                            expiry_time: '2024-06-06T23:29:11.914Z',
                        },
                    },
                },
                {
                    object: 'block',
                    id: '66512629-96d8-4f71-8be6-05cabca44f45',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T03:02:00.000Z',
                    last_edited_time: '2024-01-30T14:17:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'image',
                    image: {
                        caption: [
                            {
                                type: 'text',
                                text: {
                                    content: 'Fund detail',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'Fund detail',
                                href: null,
                            },
                        ],
                        type: 'file',
                        file: {
                            url: '/projects/dragonx/fund-detail.png',
                            expiry_time: '2024-06-06T23:29:11.927Z',
                        },
                    },
                },
                {
                    object: 'block',
                    id: '3b9bdcfd-be4b-4c50-a389-109065ff758d',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T14:34:00.000Z',
                    last_edited_time: '2024-03-06T00:03:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'image',
                    image: {
                        caption: [
                            {
                                type: 'text',
                                text: {
                                    content: 'Portfolio screen',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'Portfolio screen',
                                href: null,
                            },
                        ],
                        type: 'file',
                        file: {
                            url: '/projects/dragonx/portfolio.png',
                            expiry_time: '2024-06-06T23:29:12.008Z',
                        },
                    },
                },
                {
                    object: 'block',
                    id: '3a067b1f-f17c-41ac-bb0a-2735ce98811b',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T03:24:00.000Z',
                    last_edited_time: '2024-03-06T00:04:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'image',
                    image: {
                        caption: [
                            {
                                type: 'text',
                                text: {
                                    content: 'Transaction screen',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'Transaction screen',
                                href: null,
                            },
                        ],
                        type: 'file',
                        file: {
                            url: '/projects/dragonx/buy.png',
                            expiry_time: '2024-06-06T23:29:11.979Z',
                        },
                    },
                },
                {
                    object: 'block',
                    id: '7cf70a3a-741e-4924-8a67-75ee18a50937',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T03:07:00.000Z',
                    last_edited_time: '2024-01-30T13:06:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'image',
                    image: {
                        caption: [
                            {
                                type: 'text',
                                text: {
                                    content: 'Dragon library screen',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'Dragon library screen',
                                href: null,
                            },
                        ],
                        type: 'file',
                        file: {
                            url: '/projects/dragonx/dragon-lib.png',
                            expiry_time: '2024-06-06T23:29:11.993Z',
                        },
                    },
                },
                {
                    object: 'block',
                    id: '7cf70a3a-741e-4924-8a67-75ee18a50937',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T03:07:00.000Z',
                    last_edited_time: '2024-01-30T13:06:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'image',
                    image: {
                        caption: [
                            {
                                type: 'text',
                                text: {
                                    content: 'History screen',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'History screen',
                                href: null,
                            },
                        ],
                        type: 'file',
                        file: {
                            url: '/projects/dragonx/history.png',
                            expiry_time: '2024-06-06T23:29:11.993Z',
                        },
                    },
                },
            ],
        },
        {
            id: '85808fd2-2277-4eae-a77c-505240ce678s',
            title: '25 FIT Platform',
            listed: true,
            slug: '25fit',
            type: 'Front End Developer',
            cover: '/projects/25fit/25fit.jpg',
            client: '25 FIT',
            clientLogo: null,
            partner: null,
            completed: 'Jun 2023 - Dec 2023',
            site: '25fit.com',
            stack: [
                {
                    id: '923a339b-6c21-4777-a18d-99d6525c8840',
                    name: 'Nuxt',
                    color: 'green',
                },
                {
                    id: '923a339b-6c21-4777-a18d-99d6525c8840',
                    name: 'Vue',
                    color: 'green',
                },
                {
                    id: '923a339b-6c21-4777-a18d-99d6525c8840',
                    name: 'Composition API',
                    color: 'purple',
                },
            ],
            role: 'Front End Developer',
            lead: 'Building the new platform for 25 FIT.',
            awards: null,
            pageContent: [
                {
                    object: 'block',
                    id: '8297cd08-c819-4455-bfe6-d3e948e6dc07',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-23T14:58:00.000Z',
                    last_edited_time: '2024-03-05T23:57:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'paragraph',
                    paragraph: {
                        rich_text: [
                            {
                                type: 'text',
                                text: {
                                    content: 'An innovative gym business based in Vietnam, pioneering the use of Electric Muscle Stimulation (EMS) technology to revolutionize fitness training. With a focus on efficiency and convenience, the core offering users to book personalized training sessions through a mobile app, choosing the location, training objectives, and suit size. Cutting-edge system streamlines coach assignments, session management, and payment processing.',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'An innovative gym business based in Vietnam, pioneering the use of Electric Muscle Stimulation (EMS) technology to revolutionize fitness training. With a focus on efficiency and convenience, the core offering users to book personalized training sessions through a mobile app, choosing the location, training objectives, and suit size. Cutting-edge system streamlines coach assignments, session management, and payment processing.',
                                href: null,
                            },
                        ],
                        color: 'default',
                    },
                },
                {
                    object: 'block',
                    id: '1db6580a-87dc-4561-90f8-e6fc40830611',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T13:07:00.000Z',
                    last_edited_time: '2024-01-30T13:07:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'image',
                    image: {
                        caption: [],
                        type: 'file',
                        file: {
                            url: '/projects/dragonx/home.png',
                            expiry_time: '2024-06-06T23:29:11.914Z',
                        },
                    },
                },
                {
                    object: 'block',
                    id: '5fcaac2a-0617-4c41-9ee8-1d2863bdba42',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T03:29:00.000Z',
                    last_edited_time: '2024-03-05T23:58:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'paragraph',
                    paragraph: {
                        rich_text: [
                            {
                                type: 'text',
                                text: {
                                    content: 'I cloned the repo and started getting familiar with the existing VitePress installation used for the docs site. My plan of attack was to put in place an initial framing for each section, and then build one component at a time. As things came together, I found ways to centralize logic into composables and make things more efficient and organized. That seems to be my approach no matter what I’m building - get ',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'I cloned the repo and started getting familiar with the existing VitePress installation used for the docs site. My plan of attack was to put in place an initial framing for each section, and then build one component at a time. As things came together, I found ways to centralize logic into composables and make things more efficient and organized. That seems to be my approach no matter what I’m building - get ',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: 'something',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: true,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'something',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: ' in place early, and then make iterative improvements until it’s production-ready. My best work comes from improving something, versus starting from scratch.',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: ' in place early, and then make iterative improvements until it’s production-ready. My best work comes from improving something, versus starting from scratch.',
                                href: null,
                            },
                        ],
                        color: 'default',
                    },
                },
                {
                    object: 'block',
                    id: 'e7d76801-1029-44ca-af72-82570ba20cd3',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T03:35:00.000Z',
                    last_edited_time: '2024-03-05T23:58:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'paragraph',
                    paragraph: {
                        rich_text: [
                            {
                                type: 'text',
                                text: {
                                    content: 'There were some limitations to keep in mind with this. It was clear early on that I couldn’t add dependencies to the Vite codebase unless it was critical to do so, as they would be shipped with Vite on every future download. I ended up adding ',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'There were some limitations to keep in mind with this. It was clear early on that I couldn’t add dependencies to the Vite codebase unless it was critical to do so, as they would be shipped with Vite on every future download. I ended up adding ',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: 'gsap',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: true,
                                    color: 'default',
                                },
                                plain_text: 'gsap',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: ' as the only new dev dependency to tackle the more complex animations. I also wanted to achieve no less than 60fps @ 4k resolution on moderate hardware and have the page load near-instantaneously, considering the reputation Vite has for being lightning-fast. On my own machine, I was pulling 120fps @ 4k.',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: ' as the only new dev dependency to tackle the more complex animations. I also wanted to achieve no less than 60fps @ 4k resolution on moderate hardware and have the page load near-instantaneously, considering the reputation Vite has for being lightning-fast. On my own machine, I was pulling 120fps @ 4k.',
                                href: null,
                            },
                        ],
                        color: 'default',
                    },
                },
                {
                    object: 'block',
                    id: '66512629-96d8-4f71-8be6-05cabca44f45',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T03:02:00.000Z',
                    last_edited_time: '2024-01-30T14:17:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'image',
                    image: {
                        caption: [
                            {
                                type: 'text',
                                text: {
                                    content: 'Detailed views for each component state, mocked in Figma.',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'Detailed views for each component state, mocked in Figma.',
                                href: null,
                            },
                        ],
                        type: 'file',
                        file: {
                            url: 'https://prod-files-secure.s3.us-west-2.amazonaws.com/ba27abef-4bbc-4834-b02a-65197fa7427a/222d9f32-4afa-4dc4-b7a2-6e21d0599396/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45HZZMZUHI%2F20240606%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20240606T222911Z&X-Amz-Expires=3600&X-Amz-Signature=ad43018f9a9413d538c054ce548f6fb371ba2fb67806cac130462ea7abc75558&X-Amz-SignedHeaders=host&x-id=GetObject',
                            expiry_time: '2024-06-06T23:29:11.927Z',
                        },
                    },
                },
                {
                    object: 'block',
                    id: '11aa5c4a-e786-4e57-97f8-310ef62cc356',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-23T14:58:00.000Z',
                    last_edited_time: '2024-01-30T14:29:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'paragraph',
                    paragraph: {
                        rich_text: [
                            {
                                type: 'text',
                                text: {
                                    content: 'I was provided a Figma board with everything I would need, designed by ',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'I was provided a Figma board with everything I would need, designed by ',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: 'Vincent Rodriguez',
                                    link: {
                                        url: 'https://www.rmoon.me/',
                                    },
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'Vincent Rodriguez',
                                href: 'https://www.rmoon.me/',
                            },
                            {
                                type: 'text',
                                text: {
                                    content: ', a UI & Brand Designer formerly at NuxtLabs. Thanks to his well-organized designs, it was clear to see how things needed to come together, allowing me to work a lot more asynchronously. He’d also fully mocked up the animation sequences, using Figma magic that’s above my pay-grade.',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: ', a UI & Brand Designer formerly at NuxtLabs. Thanks to his well-organized designs, it was clear to see how things needed to come together, allowing me to work a lot more asynchronously. He’d also fully mocked up the animation sequences, using Figma magic that’s above my pay-grade.',
                                href: null,
                            },
                        ],
                        color: 'default',
                    },
                },
                {
                    object: 'block',
                    id: '4fe9982a-31c6-4c2b-b28a-05d7429496ad',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-23T14:58:00.000Z',
                    last_edited_time: '2024-01-30T14:31:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'paragraph',
                    paragraph: {
                        rich_text: [
                            {
                                type: 'text',
                                text: {
                                    content: 'Getting into it, my methodology for approaching animations was that simple shapes would be created in the DOM and animated using CSS to the extent possible, and that more intricately animated illustrations would be rendered as SVG with reactive props.',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'Getting into it, my methodology for approaching animations was that simple shapes would be created in the DOM and animated using CSS to the extent possible, and that more intricately animated illustrations would be rendered as SVG with reactive props.',
                                href: null,
                            },
                        ],
                        color: 'default',
                    },
                },
                {
                    object: 'block',
                    id: 'd8d7b133-24a9-4eaa-9e85-36ce5a3c9faf',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T14:18:00.000Z',
                    last_edited_time: '2024-01-30T14:31:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'paragraph',
                    paragraph: {
                        rich_text: [
                            {
                                type: 'text',
                                text: {
                                    content: 'The main Vite CPU “chip” in the hero animation is a good example of using CSS-first animations. The reflective highlight is achieved by passing two linear gradients at different angles and speeds over the surface, rounding it out, blurring, and using a color-dodge blend mode. This helps it feel organic, curved and random - despite it really just being two rectangles. The specular edges use a little known quirk of Chromium-based browsers to transition between various gradients; creating a sense of constantly moving environment lighting.',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'The main Vite CPU “chip” in the hero animation is a good example of using CSS-first animations. The reflective highlight is achieved by passing two linear gradients at different angles and speeds over the surface, rounding it out, blurring, and using a color-dodge blend mode. This helps it feel organic, curved and random - despite it really just being two rectangles. The specular edges use a little known quirk of Chromium-based browsers to transition between various gradients; creating a sense of constantly moving environment lighting.',
                                href: null,
                            },
                        ],
                        color: 'default',
                    },
                },
                {
                    object: 'block',
                    id: '3b9bdcfd-be4b-4c50-a389-109065ff758d',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T14:34:00.000Z',
                    last_edited_time: '2024-03-06T00:03:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'image',
                    image: {
                        caption: [
                            {
                                type: 'text',
                                text: {
                                    content: 'Per-path radial glow creates variance in animation speed, versus a linear vertical “wipe”.',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'Per-path radial glow creates variance in animation speed, versus a linear vertical “wipe”.',
                                href: null,
                            },
                        ],
                        type: 'file',
                        file: {
                            url: 'https://prod-files-secure.s3.us-west-2.amazonaws.com/ba27abef-4bbc-4834-b02a-65197fa7427a/e5215f60-7253-4ca1-b14f-df2b9738a8fd/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45HZZMZUHI%2F20240606%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20240606T222912Z&X-Amz-Expires=3600&X-Amz-Signature=6835b243e22d3b0c0e9eb21a585f998e8813733dc41be9bbd278389e906da80a&X-Amz-SignedHeaders=host&x-id=GetObject',
                            expiry_time: '2024-06-06T23:29:12.008Z',
                        },
                    },
                },
                {
                    object: 'block',
                    id: 'fc8932df-7127-4638-a83c-ffdab513db03',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T14:18:00.000Z',
                    last_edited_time: '2024-01-30T14:35:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'paragraph',
                    paragraph: {
                        rich_text: [
                            {
                                type: 'text',
                                text: {
                                    content: 'The glowing nodes moving along the curved paths in the animations are where SVG animations came into play. To achieve the effect, I put together a component that could accept props such as a ',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'The glowing nodes moving along the curved paths in the animations are where SVG animations came into play. To achieve the effect, I put together a component that could accept props such as a ',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: 'path',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: true,
                                    color: 'default',
                                },
                                plain_text: 'path',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: ', ',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: ', ',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: 'position',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: true,
                                    color: 'default',
                                },
                                plain_text: 'position',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: ', ',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: ', ',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: 'color',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: true,
                                    color: 'default',
                                },
                                plain_text: 'color',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: ', etc. and render an SVG element appropriately. It positions the glow by shifting a radial gradient over the line and then masking it with the original SVG path, allowing it to wrap around corners smoothly and vertically. GSAP was then used to animate those props over time.',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: ', etc. and render an SVG element appropriately. It positions the glow by shifting a radial gradient over the line and then masking it with the original SVG path, allowing it to wrap around corners smoothly and vertically. GSAP was then used to animate those props over time.',
                                href: null,
                            },
                        ],
                        color: 'default',
                    },
                },
                {
                    object: 'block',
                    id: 'f8ed4542-ea41-4b16-9c53-aef74ea5254d',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T13:06:00.000Z',
                    last_edited_time: '2024-01-30T14:25:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'paragraph',
                    paragraph: {
                        rich_text: [
                            {
                                type: 'text',
                                text: {
                                    content: 'Wherever possible, I found ways to be more efficient with the rendering to maintain consistently high frame rates. The gradient background on the hero section is a prime example. Originally I had used two colored circles with a very large blur filter based on the viewport sizing. This worked well on desktop, but was a little sluggish on mobile devices. A better option was to use a single background gradient to get the color correct, and then an image-mask with a radial gradient to get the lighting correct. A layer of light grain ',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'Wherever possible, I found ways to be more efficient with the rendering to maintain consistently high frame rates. The gradient background on the hero section is a prime example. Originally I had used two colored circles with a very large blur filter based on the viewport sizing. This worked well on desktop, but was a little sluggish on mobile devices. A better option was to use a single background gradient to get the color correct, and then an image-mask with a radial gradient to get the lighting correct. A layer of light grain ',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: '(a very small PNG file)',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: true,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: '(a very small PNG file)',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: ' added texture and helped to reduce color banding in the CSS gradients. Overall the effect looked the same ',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: ' added texture and helped to reduce color banding in the CSS gradients. Overall the effect looked the same ',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: '(or better)',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: true,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: '(or better)',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: ' with less hit on the GPU. This helped improve responsiveness for mobile devices on first load, considering the effect was above-the-fold.',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: ' with less hit on the GPU. This helped improve responsiveness for mobile devices on first load, considering the effect was above-the-fold.',
                                href: null,
                            },
                        ],
                        color: 'default',
                    },
                },
                {
                    object: 'block',
                    id: '3a067b1f-f17c-41ac-bb0a-2735ce98811b',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T03:24:00.000Z',
                    last_edited_time: '2024-03-06T00:04:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'image',
                    image: {
                        caption: [
                            {
                                type: 'text',
                                text: {
                                    content: 'One of two sections of bento-style cards, where each card’s animation is triggered on hover on desktop, or scroll on mobile.',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'One of two sections of bento-style cards, where each card’s animation is triggered on hover on desktop, or scroll on mobile.',
                                href: null,
                            },
                        ],
                        type: 'file',
                        file: {
                            url: 'https://prod-files-secure.s3.us-west-2.amazonaws.com/ba27abef-4bbc-4834-b02a-65197fa7427a/2afdc485-31ab-4e7c-9632-6e2fcaa041c6/Laptop_1.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45HZZMZUHI%2F20240606%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20240606T222911Z&X-Amz-Expires=3600&X-Amz-Signature=813cf956f98d608f41c00a606b0440d198c7f850667f7e5cc33b76e6e70bf857&X-Amz-SignedHeaders=host&x-id=GetObject',
                            expiry_time: '2024-06-06T23:29:11.979Z',
                        },
                    },
                },
                {
                    object: 'block',
                    id: '88b4788d-70d9-4392-8d92-200fc8f4f105',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-23T16:56:00.000Z',
                    last_edited_time: '2024-03-06T00:04:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'paragraph',
                    paragraph: {
                        rich_text: [
                            {
                                type: 'text',
                                text: {
                                    content: 'For Vite’s feature cards, combinations of similar CSS and JS driven animations were configured, with reusable logic placed within composables. For example, one composable attached GSAP ',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'For Vite’s feature cards, combinations of similar CSS and JS driven animations were configured, with reusable logic placed within composables. For example, one composable attached GSAP ',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: 'ScrollTrigger',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: true,
                                    color: 'default',
                                },
                                plain_text: 'ScrollTrigger',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: ' listeners when mounted, watching for elements to scroll into view ',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: ' listeners when mounted, watching for elements to scroll into view ',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: '(on mobile)',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: true,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: '(on mobile)',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: ' and starting a callback animation defined by the individual card. On desktop this could easily be triggered by running the callback on a ',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: ' and starting a callback animation defined by the individual card. On desktop this could easily be triggered by running the callback on a ',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: 'mouseover',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: true,
                                    color: 'default',
                                },
                                plain_text: 'mouseover',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: ' event listener instead.',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: ' event listener instead.',
                                href: null,
                            },
                        ],
                        color: 'default',
                    },
                },
                {
                    object: 'block',
                    id: '477c91b5-f893-4789-a1e5-27acb54bfc7e',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-03-06T00:01:00.000Z',
                    last_edited_time: '2024-03-06T00:03:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'paragraph',
                    paragraph: {
                        rich_text: [
                            {
                                type: 'text',
                                text: {
                                    content: 'These individual cards had a lot of attention to detail placed on them, where Vue’s component architecture made it easy to isolate and work on them individually with scoped CSS, state and logic. As mentioned earlier, each one was initially stubbed out as just an SVG image before undergoing passes of improvement until they were feature-complete and ready for production.',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'These individual cards had a lot of attention to detail placed on them, where Vue’s component architecture made it easy to isolate and work on them individually with scoped CSS, state and logic. As mentioned earlier, each one was initially stubbed out as just an SVG image before undergoing passes of improvement until they were feature-complete and ready for production.',
                                href: null,
                            },
                        ],
                        color: 'default',
                    },
                },
                {
                    object: 'block',
                    id: '7cf70a3a-741e-4924-8a67-75ee18a50937',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T03:07:00.000Z',
                    last_edited_time: '2024-01-30T13:06:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'image',
                    image: {
                        caption: [],
                        type: 'file',
                        file: {
                            url: 'https://prod-files-secure.s3.us-west-2.amazonaws.com/ba27abef-4bbc-4834-b02a-65197fa7427a/29a16482-0c27-43d3-919e-317d31ebc62c/Mobile_1.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45HZZMZUHI%2F20240606%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20240606T222912Z&X-Amz-Expires=3600&X-Amz-Signature=cad3d3b20b95075ef547295b518bb148ddbe6e15201e65e039b8e243c6d447c5&X-Amz-SignedHeaders=host&x-id=GetObject',
                            expiry_time: '2024-06-06T23:29:11.993Z',
                        },
                    },
                },
                {
                    object: 'block',
                    id: '0f2e8d7c-54a5-4841-b5b5-aad6de57cc66',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-23T14:58:00.000Z',
                    last_edited_time: '2024-01-30T14:24:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'paragraph',
                    paragraph: {
                        rich_text: [
                            {
                                type: 'text',
                                text: {
                                    content: 'Mobile saw a slight reduction of some of the heavier effects to keep runtime performance fast. Most of the time that meant dropping transparency and any sort of backdrop/object blur, as those are particularly resource intensive effects. The hero animation is also swapped out for a simplified version that better fits within the mobile viewport.',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'Mobile saw a slight reduction of some of the heavier effects to keep runtime performance fast. Most of the time that meant dropping transparency and any sort of backdrop/object blur, as those are particularly resource intensive effects. The hero animation is also swapped out for a simplified version that better fits within the mobile viewport.',
                                href: null,
                            },
                        ],
                        color: 'default',
                    },
                },
                {
                    object: 'block',
                    id: 'aed43c6e-03c2-4970-845d-83d5d7e39965',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T14:39:00.000Z',
                    last_edited_time: '2024-01-30T14:47:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'paragraph',
                    paragraph: {
                        rich_text: [
                            {
                                type: 'text',
                                text: {
                                    content: 'For all animations, CSS properties that were tweened were kept as GPU-friendly as possible, utilizing ',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'For all animations, CSS properties that were tweened were kept as GPU-friendly as possible, utilizing ',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: 'will-change',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: true,
                                    color: 'default',
                                },
                                plain_text: 'will-change',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: ' and browser tricks like ',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: ' and browser tricks like ',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: 'translate3d(0,0,0)',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: true,
                                    color: 'default',
                                },
                                plain_text: 'translate3d(0,0,0)',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: ' to push animated layers to the GPU, and then only animating properties such as ',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: ' to push animated layers to the GPU, and then only animating properties such as ',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: 'opacity',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: true,
                                    color: 'default',
                                },
                                plain_text: 'opacity',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: ' and ',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: ' and ',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: 'transform',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: true,
                                    color: 'default',
                                },
                                plain_text: 'transform',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: ' to avoid repainting ',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: ' to avoid repainting ',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: '(as those get performed at compositing time)',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: true,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: '(as those get performed at compositing time)',
                                href: null,
                            },
                            {
                                type: 'text',
                                text: {
                                    content: '. Each component was also extensively tested cross-browser and tweaked at varying breakpoints.',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: '. Each component was also extensively tested cross-browser and tweaked at varying breakpoints.',
                                href: null,
                            },
                        ],
                        color: 'default',
                    },
                },
                {
                    object: 'block',
                    id: '00ccc85e-ce54-4b10-a4af-2dead5c01302',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T14:43:00.000Z',
                    last_edited_time: '2024-03-06T00:03:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'paragraph',
                    paragraph: {
                        rich_text: [
                            {
                                type: 'text',
                                text: {
                                    content: 'After a few small feedback items, the project was wrapped and the codebase cleaned up for delivery. I look forward to seeing how the Vite community reacts to the updated look and feel 👀',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'After a few small feedback items, the project was wrapped and the codebase cleaned up for delivery. I look forward to seeing how the Vite community reacts to the updated look and feel 👀',
                                href: null,
                            },
                        ],
                        color: 'default',
                    },
                },
                {
                    object: 'block',
                    id: 'b81d6c0b-5ba2-4bb0-ba1a-0c02efefeff8',
                    parent: {
                        type: 'page_id',
                        page_id: '85808fd2-2277-4eae-a77c-505240ce6787',
                    },
                    created_time: '2024-01-30T03:10:00.000Z',
                    last_edited_time: '2024-01-30T14:46:00.000Z',
                    created_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    last_edited_by: {
                        object: 'user',
                        id: '850b2956-a12b-4dd0-a6bd-d72a0f8cd68f',
                    },
                    has_children: false,
                    archived: false,
                    in_trash: false,
                    type: 'quote',
                    quote: {
                        rich_text: [
                            {
                                type: 'text',
                                text: {
                                    content: 'It\'s absolutely beautiful - amazing work!',
                                    link: null,
                                },
                                annotations: {
                                    bold: false,
                                    italic: false,
                                    strikethrough: false,
                                    underline: false,
                                    code: false,
                                    color: 'default',
                                },
                                plain_text: 'It\'s absolutely beautiful - amazing work!',
                                href: null,
                            },
                        ],
                        color: 'default',
                    },
                },
            ],
        },
    ],
})